/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thuchanh3;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Vannghia
 */
public class listviewGUI extends javax.swing.JFrame {
        DefaultListModel trai;
        DefaultListModel phai;
    /**
     * Creates new form listviewGUI
     */
    public listviewGUI() {
        initComponents();
        trai = new DefaultListModel();
        listtt.setModel(trai);
        trai.addElement("bóng đá");
        trai.addElement("bóng chuyền");
        trai.addElement("cầu lông");
        
        phai = new DefaultListModel();
        lisyt.setModel(phai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listtt = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lisyt = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnquaphai = new javax.swing.JButton();
        btnquaphaiall = new javax.swing.JButton();
        btnquatrai = new javax.swing.JButton();
        btnquatraiall = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listview Bài 3");

        jScrollPane1.setViewportView(listtt);
        listtt.getAccessibleContext().setAccessibleName("");

        jScrollPane2.setViewportView(lisyt);

        jLabel1.setText("DS Môn thể thao");

        jLabel2.setText("DS Môn yêu thích");

        btnquaphai.setText(">");
        btnquaphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquaphaiActionPerformed(evt);
            }
        });

        btnquaphaiall.setText(">>");
        btnquaphaiall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquaphaiallActionPerformed(evt);
            }
        });

        btnquatrai.setText("<");
        btnquatrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquatraiActionPerformed(evt);
            }
        });

        btnquatraiall.setText("<<");
        btnquatraiall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquatraiallActionPerformed(evt);
            }
        });

        btnthem.setText("+");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnthem)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnquaphaiall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnquaphai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnquatrai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnquatraiall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnquaphai)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnquaphaiall)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnquatrai)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnquatraiall)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnthem)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void btnquaphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquaphaiActionPerformed
        int[] vitri = listtt.getSelectedIndices();
        for(int i = vitri.length -1;i>=0;i--)
        {
            phai.addElement(trai.get(vitri[i]));
            trai.remove(vitri[i]);
        }      
    }//GEN-LAST:event_btnquaphaiActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
       String nhap = JOptionPane.showInputDialog("Nhập môn thể thao ");
        trai.addElement(nhap);
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnquaphaiallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquaphaiallActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<trai.getSize();i++)
        {
            phai.addElement(trai.get(i));
        }
        trai.clear();
    }//GEN-LAST:event_btnquaphaiallActionPerformed

    private void btnquatraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquatraiActionPerformed
        // TODO add your handling code here:
        int[] vitri = lisyt.getSelectedIndices();
        for(int i = vitri.length -1;i>=0;i--)
        {
            trai.addElement(phai.get(vitri[i]));
            phai.remove(vitri[i]);
        }
    }//GEN-LAST:event_btnquatraiActionPerformed

    private void btnquatraiallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquatraiallActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<phai.getSize();i++)
        {
            trai.addElement(phai.get(i));
        }
        phai.clear();
    }//GEN-LAST:event_btnquatraiallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listviewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listviewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listviewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listviewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listviewGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnquaphai;
    private javax.swing.JButton btnquaphaiall;
    private javax.swing.JButton btnquatrai;
    private javax.swing.JButton btnquatraiall;
    private javax.swing.JButton btnthem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listtt;
    private javax.swing.JList<String> lisyt;
    // End of variables declaration//GEN-END:variables
}
