/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai89;

/**
 *
 * @author Van Nghia
 */
import bai89.NhanVien;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Nhapthongtin extends javax.swing.JFrame {

    /**
     * Creates new form Nhapthongtin
     */
    
    private Vector<NhanVien> nv = new Vector<NhanVien>();
    DefaultTableModel ds = new DefaultTableModel
            ( new Object[][]
            {
                
            }
                    ,
                    new String []
                    {
                        "Mã nhân viên","Phân xưởng","Số sản phẩm","Vượt chuẩn"
                    }
            );
    
    public Nhapthongtin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsosp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        boxpx = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtsospchuan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtluong = new javax.swing.JTextField();
        btntinhluong = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btndong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnhanvien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhập thông tin NV");

        jLabel1.setText("Mã Nhân viên");

        jLabel2.setText("Số sản phẩm");

        jLabel3.setText("Phân xưởng");

        boxpx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        boxpx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxpxActionPerformed(evt);
            }
        });

        jLabel4.setText("Số sản phẩm chuẩn");

        txtsospchuan.setEditable(false);
        txtsospchuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsospchuanActionPerformed(evt);
            }
        });

        jLabel5.setText("Tiền lương");

        txtluong.setBackground(new java.awt.Color(153, 255, 255));
        txtluong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtluong.setBorder(null);

        btntinhluong.setText("Tính lương");
        btntinhluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntinhluongActionPerformed(evt);
            }
        });

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btndong.setText("Đóng");
        btndong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongActionPerformed(evt);
            }
        });

        tblnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Phân xưởng", "Số sản phẩm", "Vượt chuẩn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblnhanvien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45)
                        .addComponent(boxpx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsospchuan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btntinhluong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnthem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnxoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndong))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmanv)
                                    .addComponent(txtsosp)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txtluong)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtsosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(boxpx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtsospchuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntinhluong)
                    .addComponent(btnthem)
                    .addComponent(btnxoa)
                    .addComponent(btnsua)
                    .addComponent(btndong))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
       //Thêm vào vector NhanVien
       
       
       NhanVien hangmoi = new NhanVien();
       hangmoi.setManv(txtmanv.getText());
       hangmoi.setPx(boxpx.getSelectedItem().toString());
       hangmoi.setSosp(Integer.parseInt(txtsosp.getText()));
       nv.add(hangmoi);
       
       //Thêm vào table
        Vector<String> hang = new Vector<String>();
        hang.add(hangmoi.getManv());
        hang.add(hangmoi.getPx());
        hang.add(txtsosp.getText());
        if(hangmoi.VuotChuan() == true ) hang.add("X");
        else hang.add("");
        ds.addRow(hang);
        tblnhanvien.setModel(ds);
        
        
        txtmanv.setText("");
        txtsosp.setText("");
        txtluong.setText("");
        txtsospchuan.setText("");
    }//GEN-LAST:event_btnthemActionPerformed

    private void btntinhluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntinhluongActionPerformed
        int i = tblnhanvien.getSelectedRow();
        txtluong.setText(String.valueOf(nv.elementAt(i).TinhLuong()));
    }//GEN-LAST:event_btntinhluongActionPerformed

    private void btndongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btndongActionPerformed

    private void boxpxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxpxActionPerformed
        if(boxpx.getSelectedItem() == "A") txtsospchuan.setText("300");
        else txtsospchuan.setText("500");
    }//GEN-LAST:event_boxpxActionPerformed

    private void txtsospchuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsospchuanActionPerformed

    }//GEN-LAST:event_txtsospchuanActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        int kt = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa",
                                                    "Thông báo",
                                                    JOptionPane.YES_NO_OPTION);
        if(kt == JOptionPane.YES_OPTION)
        {
            int i = tblnhanvien.getSelectedRow();
            if(i>-1)
            {
            nv.removeElementAt(i);
            ds.removeRow(i);
            tblnhanvien.setModel(ds);         
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        int i =  tblnhanvien.getSelectedRow();
        NhanVien dsNV = new NhanVien();
        dsNV.setManv(txtmanv.getText());
        dsNV.setPx(boxpx.getSelectedItem().toString());
        dsNV.setSosp(Integer.parseInt(txtsosp.getText()));
        nv.setElementAt(dsNV, i);
        ds.setValueAt(dsNV.getManv(), i, 0);
        ds.setValueAt(dsNV.getPx(),i,1);
        ds.setValueAt(dsNV.getSosp(),i,2);
        if(dsNV.VuotChuan() == true ) ds.setValueAt("X",i,3);
        else ds.setValueAt("",i,3);
        
    }//GEN-LAST:event_btnsuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nhapthongtin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nhapthongtin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nhapthongtin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nhapthongtin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nhapthongtin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxpx;
    private javax.swing.JButton btndong;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntinhluong;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblnhanvien;
    private javax.swing.JTextField txtluong;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txtsosp;
    private javax.swing.JTextField txtsospchuan;
    // End of variables declaration//GEN-END:variables
}
